# Generated by Django 6.1.1 on 2026-10-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField()),
                ('sex', models.CharField(choices=[('MALE', 'Hombre'), ('FEMALE', 'Mujer')], max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activity_level', models.CharField(choices=[('NONE', 'Nula'), ('LOW', 'Poco'), ('MODERATE', 'Moderada'), ('HIGH', 'Alta'), ('VERY_HIGH', 'Muy alta')], max_length=10)),
                ('nutrition_goal', models.CharField(choices=[('WEIGHT_LOSS', 'Pérdida de peso'), ('WEIGHT_MAINTENANCE', 'Mantenimiento de peso'), ('WEIGHT_GAIN', 'Aumento de peso'), ('HEALTHY_EATING', 'Alimentación saludable')], max_length=20)),
            ],
        ),
    ]
