# Generated by Django 6.1.1 on 2026-10-08 05:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('age', models.PositiveSmallIntegerField()),
                ('sex', models.CharField(choices=[('MALE', 'Hombre'), ('FEMALE', 'Mujer')], max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activity_level', models.CharField(choices=[('NONE', 'Nula'), ('LOW', 'Poco'), ('MODERATE', 'Moderada'), ('HIGH', 'Alta'), ('VERY_HIGH', 'Muy alta')], max_length=10)),
                ('nutrition_goal', models.CharField(choices=[('WEIGHT_LOSS', 'Pérdida de peso'), ('WEIGHT_MAINTENANCE', 'Mantenimiento de peso'), ('WEIGHT_GAIN', 'Aumento de peso'), ('HEALTHY_EATING', 'Alimentación saludable')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('serving_size', models.DecimalField(decimal_places=2, max_digits=8)),
                ('serving_unit', models.CharField(choices=[('G', 'Gramos'), ('ML', 'Mililitros'), ('UNIT', 'Unidad')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='nutrition.foodcategory')),
            ],
        ),
        migrations.CreateModel(
            name='FoodNutrient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nutrient_type', models.CharField(choices=[('CALORIES', 'Calorías'), ('PROTEIN', 'Proteínas'), ('CARBOHYDRATES', 'Carbohidratos'), ('FAT', 'Grasas'), ('FIBER', 'Fibra'), ('SUGAR', 'Azúcares'), ('SODIUM', 'Sodio')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(choices=[('G', 'Gramos'), ('MG', 'Miligramos'), ('KCAL', 'Kilocalorías')], max_length=10)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='nutrition.food')),
            ],
        ),
    ]
