# Generated by Django 6.1.1 on 2026-10-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionalprofile',
            name='user_id',
            field=models.UUIDField(),
        ),
    ]
