# Generated by Django 6.1.1 on 2026-10-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_nutritionalprofile_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=8)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=8)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fiber', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sugar', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
